excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
identifier_name:
  excluded:
    - to
    - T
    - S
line_length:
  warning: 180
  error: 200
disabled_rules:
  - force_try
  - force_cast
  - nesting
  - multiple_closures_with_trailing_closure
